# Site title and subtitle. This is used in _includes/header.html
title: 'SegmentStream documentation'
subtitle: ''

collections:
  docs:
    output: true
    permalink: /:path

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

# Default categories (in order) to appear in the navigation
sections: [
    ['BigQuery project', [
        ['bigquery', 'BigQuery Setup'],
        ['datasources', 'Data Sources'],
        ['datadestinations', 'Data Destinations'],
        ['javascript-sdk', 'JavaScript SDK'],
        ['digitaldata', 'DigitalData Variables'],
        ['events', 'DigitalData Events'],
        ['ecommerce', 'DigitalData for Ecommerce'],
        ['integrations', 'Tracking Integrations'],
        ['http-api', 'HTTP API'],
        ['guides', 'Guides']
    ]],
    ['Google Analytics project', [
        ['google-analytics', 'Google Analytics Setup'],
        ['ga-datasources', 'Data Sources'],
    ]]
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
timezone: 'Europe/Moscow'
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
